name: Build, Test & Package

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'docs/**' # Don't run workflow when files are only in the /docs directory

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build Build.csproj -c Release --nologo /p:CI=true
    - name: Test
      run: dotnet test Build.csproj -c Release --no-build --nologo /p:CI=true
    - name: Tool Restore
      working-directory: tests
      run: dotnet tool restore
    - name: Code coverage
      run: dotnet test Build.csproj -c Release --no-build --nologo /p:CI=true --collect:"XPlat Code Coverage" 
    - name: Code coverage report generation
      working-directory: tests
      run:  dotnet reportgenerator -reports:NFig.AspNetCore.Tests/TestResults/*/coverage.cobertura.xml -targetdir:$GITHUB_WORKSPACE/.coverage -reporttypes:HtmlInline;Badges
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: .coverage/*.html
  build-windows:
    needs: build-ubuntu
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build Build.csproj -c Release --nologo /p:CI=true
    - name: Test
      run: dotnet test Build.csproj -c Release --no-build --nologo /p:CI=true
    - name: Pack
      run: dotnet pack Build.csproj --no-build -c Release --nologo /p:PackageOutputPath=${env:GITHUB_WORKSPACE}\.nupkgs /p:CI=true
    - name: Push to MyGet
      run: dotnet nuget push ${env:GITHUB_WORKSPACE}\.nupkgs\*.nupkg -s https://www.myget.org/F/stackoverflow/api/v2/package -k ${{ secrets.MYGET_API_KEY }}